{
  imports = [
    # ./neovim-trunk.nix
    ./autopairs.nix
    ./cmp-nvim-lsp.nix
    ./comment.nix
    ./conform.nix
    ./cursorline.nix
    ./fidget.nix
    ./git-conflict.nix
    ./gitsigns.nix
    ./hardtime.nix
    ./lazydev.nix
    ./lint.nix
    ./lsp.nix
    ./luasnip.nix
    ./mini.nix
    ./numbertoggle.nix
    ./nvim-cmp.nix
    ./nvim-tree.nix
    ./render-markdown.nix
    ./sleuth.nix
    ./smartcolumn.nix
    ./telescope.nix
    ./treesitter.nix
    ./twilight.nix
    ./venv-selector.nix
    ./which-key.nix
  ];
}
