{
  imports = [
    ./alpha.nix
    ./autopairs.nix
    ./comment.nix
    ./conform.nix
    ./cursorline.nix
    ./gitsigns.nix
    ./lint.nix
    ./lsp.nix
    ./mini.nix
    ./nvim-cmp.nix
    ./sleuth.nix
    ./smartcolumn.nix
    ./telescope.nix
    ./treesitter.nix
    ./venv-selector.nix
    ./which-key.nix
  ];
}
