# modules/home/gtk.nix
# GTK theme configuration
{...}: {
  flake.homeModules.gtk = {pkgs, ...}: {
    gtk = {
      enable = true;

      #
      # Cursors are being managed under `home.pointerCursors`
      # note to self: do not use `gtk.cursorTheme`
      #
      # GTK3/GTK4 themes are generated by Stylix (rose-pine-moon, adw-gtk3 base)
      # via `stylix.targets.gtk`. Do not set `gtk.theme` / `gtk.gtk4.theme`
      # here — Stylix defines them and any value here conflicts.
      #

      iconTheme = {
        package = pkgs.candy-icons;
        name = "candy-icons";
      };

      gtk3.extraConfig = {
        gtk-application-prefer-dark-theme = 1;
      };

      gtk4 = {
        extraConfig = {
          gtk-application-prefer-dark-theme = 1;
        };
      };
    };
  };
}
