#!/usr/bin/env python3

import docker
import argparse


plex_image = 'plexinc/pms-docker:latest'
client = docker.from_env()

parser = argparse.ArgumentParser(description='Control Plex on Docker')
parser.add_argument('command',
                    help='Start, update or stop Plex container.',
                    nargs='?',
                    const=str)
parser.add_argument('--name',
                    help='Container name being used for Plex.',
                    nargs='?',
                    const=str,
                    default='plex')


def update():
    client.images.pull(plex_image)

if __name__ == "__main__":
    args = parser.parse_args()
    cmd = args.command
    name = args.name

    if not cmd or cmd not in ['start', 'update', 'stop']:
        parser.print_help()
    elif cmd == 'start':
        client.api.start(name)
    elif cmd == 'update':
        client.images.pull(plex_image)
    else:
        client.api.stop(name)
