#!/bin/sh

monitor_left="HDMI-A-0"
monitor_center="DisplayPort-2"
# monitor_right="DisplayPort-1"

# fix display order
xrandr \
  --output $monitor_left --mode 1920x1080 --pos 0x0 --rotate normal \
  --output $monitor_center --primary --mode 2560x1080 --pos 1920x0 --rotate normal
  # --output $monitor_right --mode 1920x1080 --pos 4480x0 --rotate normal

# set proper nvidia settings
# nvidia-settings --assign CurrentMetaMode="
# DPY-0: nvidia-auto-select @2560x1080 +1920+0 {ViewPortIn=2560x1080, ViewPortOut=2560x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, 
# DPY-3: nvidia-auto-select @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}, 
# DPY-5: nvidia-auto-select @1920x1080 +4480+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}"

# fix wallpaper
nitrogen --restore

# fix conky extension
killall conky
start_conky_custom
